// Mocks generated by Mockito 5.4.4 from annotations
// in bdnewsreader/test/unit/domain/use_cases/news/bookmark_article_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bdnewsreader/core/architecture/either.dart' as _i4;
import 'package:bdnewsreader/core/architecture/failure.dart' as _i5;
import 'package:bdnewsreader/domain/entities/news_article.dart' as _i6;
import 'package:bdnewsreader/domain/repositories/news_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NewsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRepository extends _i1.Mock implements _i2.NewsRepository {
  MockNewsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>> getNewsFeed({
    required int? page,
    required int? limit,
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNewsFeed,
          [],
          {
            #page: page,
            #limit: limit,
            #category: category,
          },
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>(
          this,
          Invocation.method(
            #getNewsFeed,
            [],
            {
              #page: page,
              #limit: limit,
              #category: category,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.NewsArticle>> getArticleById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticleById,
          [id],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.AppFailure, _i6.NewsArticle>>.value(
                _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.NewsArticle>>(
          this,
          Invocation.method(
            #getArticleById,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.NewsArticle>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> bookmarkArticle(
          String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookmarkArticle,
          [articleId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #bookmarkArticle,
            [articleId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> unbookmarkArticle(
          String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unbookmarkArticle,
          [articleId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #unbookmarkArticle,
            [articleId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<
      _i4.Either<_i5.AppFailure,
          List<_i6.NewsArticle>>> getBookmarkedArticles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookmarkedArticles,
          [],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>(
          this,
          Invocation.method(
            #getBookmarkedArticles,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> markAsRead(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [articleId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #markAsRead,
            [articleId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>> searchArticles({
    required String? query,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchArticles,
          [],
          {
            #query: query,
            #limit: limit,
          },
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>(
          this,
          Invocation.method(
            #searchArticles,
            [],
            {
              #query: query,
              #limit: limit,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>);

  @override
  _i3.Future<
      _i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>> getArticlesByCategory(
    String? category, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticlesByCategory,
          [category],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>(
          this,
          Invocation.method(
            #getArticlesByCategory,
            [category],
            {
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, List<_i6.NewsArticle>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> shareArticle(
          String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareArticle,
          [articleId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #shareArticle,
            [articleId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);
}
