// Mocks generated by Mockito 5.4.4 from annotations
// in bdnewsreader/test/unit/core/language_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bdnewsreader/core/architecture/either.dart' as _i4;
import 'package:bdnewsreader/core/architecture/failure.dart' as _i5;
import 'package:bdnewsreader/core/enums/theme_mode.dart' as _i6;
import 'package:bdnewsreader/domain/repositories/settings_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.AppThemeMode>> getThemeMode() =>
      (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.AppFailure, _i6.AppThemeMode>>.value(
                _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.AppThemeMode>>(
          this,
          Invocation.method(
            #getThemeMode,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.AppThemeMode>>);

  @override
  _i6.AppThemeMode getThemeModeSync() => (super.noSuchMethod(
        Invocation.method(
          #getThemeModeSync,
          [],
        ),
        returnValue: _i6.AppThemeMode.system,
      ) as _i6.AppThemeMode);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> setThemeMode(
          _i6.AppThemeMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #setThemeMode,
            [mode],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, double>> getReaderLineHeight() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReaderLineHeight,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, double>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, double>>(
          this,
          Invocation.method(
            #getReaderLineHeight,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, double>>);

  @override
  double getReaderLineHeightSync() => (super.noSuchMethod(
        Invocation.method(
          #getReaderLineHeightSync,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> setReaderLineHeight(
          double? height) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReaderLineHeight,
          [height],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #setReaderLineHeight,
            [height],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, double>> getReaderContrast() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReaderContrast,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, double>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, double>>(
          this,
          Invocation.method(
            #getReaderContrast,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, double>>);

  @override
  double getReaderContrastSync() => (super.noSuchMethod(
        Invocation.method(
          #getReaderContrastSync,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> setReaderContrast(
          double? contrast) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReaderContrast,
          [contrast],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #setReaderContrast,
            [contrast],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> getLanguageCode() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLanguageCode,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, String>>(
          this,
          Invocation.method(
            #getLanguageCode,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, String>>);

  @override
  String getLanguageCodeSync() => (super.noSuchMethod(
        Invocation.method(
          #getLanguageCodeSync,
          [],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getLanguageCodeSync,
            [],
          ),
        ),
      ) as String);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> setLanguageCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #setLanguageCode,
          [code],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #setLanguageCode,
            [code],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, List<String>>> getRecentSearches() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentSearches,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, List<String>>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, List<String>>>(
          this,
          Invocation.method(
            #getRecentSearches,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, List<String>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> saveRecentSearch(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecentSearch,
          [query],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #saveRecentSearch,
            [query],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> clearRecentSearches() =>
      (super.noSuchMethod(
        Invocation.method(
          #clearRecentSearches,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #clearRecentSearches,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, int>> getQuizStreak() =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuizStreak,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, int>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, int>>(
          this,
          Invocation.method(
            #getQuizStreak,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> saveQuizStreak(int? streak) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveQuizStreak,
          [streak],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #saveQuizStreak,
            [streak],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, int>> getQuizHighScore() =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuizHighScore,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, int>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, int>>(
          this,
          Invocation.method(
            #getQuizHighScore,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> saveQuizHighScore(int? score) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveQuizHighScore,
          [score],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #saveQuizHighScore,
            [score],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, double>> getReaderFontSize() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReaderFontSize,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, double>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, double>>(
          this,
          Invocation.method(
            #getReaderFontSize,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, double>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> setReaderFontSize(
          double? size) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReaderFontSize,
          [size],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #setReaderFontSize,
            [size],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, int>> getReaderFontFamily() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReaderFontFamily,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, int>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, int>>(
          this,
          Invocation.method(
            #getReaderFontFamily,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> setReaderFontFamily(
          int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReaderFontFamily,
          [index],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #setReaderFontFamily,
            [index],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, int>> getReaderTheme() =>
      (super.noSuchMethod(
        Invocation.method(
          #getReaderTheme,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, int>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, int>>(
          this,
          Invocation.method(
            #getReaderTheme,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> setReaderTheme(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReaderTheme,
          [index],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #setReaderTheme,
            [index],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);
}
