include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_import: warning
    deprecated_member_use: ignore

linter:
  rules:
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: true
    always_specify_types: false
    annotate_overrides: true
    avoid_classes_with_only_static_members: true
    avoid_empty_else: true
    avoid_print: false # You might want to allow print() during development
    avoid_redundant_argument_values: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: false
    control_flow_in_finally: true
    empty_statements: true
    file_names: true
    implementation_imports: true
    no_duplicate_case_values: true
    null_closures: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    sort_constructors_first: true
    type_annotate_public_apis: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_single_cascade_in_expression_statements: true
    unnecessary_null_checks: true