// Mocks generated by Mockito 5.4.4 from annotations
// in bdnewsreader/test/widget/features/home/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bdnewsreader/domain/entities/news_article.dart' as _i4;
import 'package:bdnewsreader/infrastructure/ai/ranking/pipeline/ranking_pipeline.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RankingPipeline].
///
/// See the documentation for Mockito's code generation for more information.
class MockRankingPipeline extends _i1.Mock implements _i2.RankingPipeline {
  @override
  _i3.Future<List<_i4.NewsArticle>> rank(List<_i4.NewsArticle>? articles) =>
      (super.noSuchMethod(
        Invocation.method(
          #rank,
          [articles],
        ),
        returnValue:
            _i3.Future<List<_i4.NewsArticle>>.value(<_i4.NewsArticle>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.NewsArticle>>.value(<_i4.NewsArticle>[]),
      ) as _i3.Future<List<_i4.NewsArticle>>);

  @override
  _i3.Future<List<_i4.NewsArticle>> run(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #run,
          [category],
        ),
        returnValue:
            _i3.Future<List<_i4.NewsArticle>>.value(<_i4.NewsArticle>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.NewsArticle>>.value(<_i4.NewsArticle>[]),
      ) as _i3.Future<List<_i4.NewsArticle>>);
}
