// Mocks generated by Mockito 5.4.4 from annotations
// in bdnewsreader/test/unit/domain/use_cases/subscription/check_subscription_status_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bdnewsreader/core/architecture/either.dart' as _i4;
import 'package:bdnewsreader/core/architecture/failure.dart' as _i5;
import 'package:bdnewsreader/domain/entities/subscription.dart' as _i6;
import 'package:bdnewsreader/domain/interfaces/subscription_repository.dart'
    as _i2;
import 'package:in_app_purchase/in_app_purchase.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i2.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>
      getCurrentSubscription() => (super.noSuchMethod(
            Invocation.method(
              #getCurrentSubscription,
              [],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>.value(
                _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.Subscription>>(
              this,
              Invocation.method(
                #getCurrentSubscription,
                [],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, bool>> canAccessFeature(
          String? featureId) =>
      (super.noSuchMethod(
        Invocation.method(
          #canAccessFeature,
          [featureId],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, bool>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, bool>>(
          this,
          Invocation.method(
            #canAccessFeature,
            [featureId],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, bool>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>> upgradeSubscription(
          _i6.SubscriptionTier? newTier) =>
      (super.noSuchMethod(
        Invocation.method(
          #upgradeSubscription,
          [newTier],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>.value(
                _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.Subscription>>(
          this,
          Invocation.method(
            #upgradeSubscription,
            [newTier],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>
      cancelSubscription() => (super.noSuchMethod(
            Invocation.method(
              #cancelSubscription,
              [],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>.value(
                _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.Subscription>>(
              this,
              Invocation.method(
                #cancelSubscription,
                [],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>
      restoreSubscription() => (super.noSuchMethod(
            Invocation.method(
              #restoreSubscription,
              [],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>.value(
                _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.Subscription>>(
              this,
              Invocation.method(
                #restoreSubscription,
                [],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>);

  @override
  _i3.Future<
      _i4.Either<_i5.AppFailure,
          Map<_i6.SubscriptionTier, List<String>>>> getAvailableTiers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableTiers,
          [],
        ),
        returnValue: _i3.Future<
            _i4.Either<_i5.AppFailure,
                Map<_i6.SubscriptionTier, List<String>>>>.value(_i7.dummyValue<
            _i4
            .Either<_i5.AppFailure, Map<_i6.SubscriptionTier, List<String>>>>(
          this,
          Invocation.method(
            #getAvailableTiers,
            [],
          ),
        )),
      ) as _i3.Future<
          _i4.Either<_i5.AppFailure, Map<_i6.SubscriptionTier, List<String>>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>
      validateAndRefreshSubscription() => (super.noSuchMethod(
            Invocation.method(
              #validateAndRefreshSubscription,
              [],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>.value(
                _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.Subscription>>(
              this,
              Invocation.method(
                #validateAndRefreshSubscription,
                [],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, bool>> isTrialEligible() =>
      (super.noSuchMethod(
        Invocation.method(
          #isTrialEligible,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, bool>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, bool>>(
          this,
          Invocation.method(
            #isTrialEligible,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, bool>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>> startTrial() =>
      (super.noSuchMethod(
        Invocation.method(
          #startTrial,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>.value(
                _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.Subscription>>(
          this,
          Invocation.method(
            #startTrial,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, int>> getTtsUsageMonth() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTtsUsageMonth,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, int>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, int>>(
          this,
          Invocation.method(
            #getTtsUsageMonth,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, int>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> incrementTtsUsage() =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementTtsUsage,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #incrementTtsUsage,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, bool>> canUseTts() =>
      (super.noSuchMethod(
        Invocation.method(
          #canUseTts,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, bool>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, bool>>(
          this,
          Invocation.method(
            #canUseTts,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, bool>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, void>> upgradeWithGooglePay({
    required _i6.SubscriptionTier? tier,
    required String? paymentToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upgradeWithGooglePay,
          [],
          {
            #tier: tier,
            #paymentToken: paymentToken,
          },
        ),
        returnValue: _i3.Future<_i4.Either<_i5.AppFailure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.AppFailure, void>>(
          this,
          Invocation.method(
            #upgradeWithGooglePay,
            [],
            {
              #tier: tier,
              #paymentToken: paymentToken,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>> processStorePurchase(
          _i8.PurchaseDetails? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #processStorePurchase,
          [purchase],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>.value(
                _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.Subscription>>(
          this,
          Invocation.method(
            #processStorePurchase,
            [purchase],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.Subscription>>);
}
