// File: android/settings.gradle.kts

pluginManagement {

   val flutterSdkPath: String = run {
        val props = java.util.Properties()
        file("local.properties").inputStream().use { props.load(it) }
        props.getProperty("flutter.sdk")
            ?: error(
                "flutter.sdk is not set in local.properties.\n" +
                "Run `flutter doctor` or set the path manually:\n" +
                "  flutter.sdk=/path/to/flutter"
            )
    }

   includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    // ─── Plugin resolution repositories ──────────────────────────────────────
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri("https://storage.googleapis.com/download.flutter.io") }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)

    repositories {
        google()
        mavenCentral()

        val flutterSdkPath: String = run {
            val props = java.util.Properties()
            file("local.properties").inputStream().use { props.load(it) }
            props.getProperty("flutter.sdk")
                ?: error("flutter.sdk is not set in local.properties")
        }
        maven {
            url = uri("$flutterSdkPath/bin/cache/artifacts/gradle_jars")
        }
        maven {
            // Flutter plugin .aar files generated by `flutter pub get`
            url = uri("${rootDir}/../.pub-cache/hosted/pub.dev")
        }
        maven {
            url = uri("https://storage.googleapis.com/download.flutter.io")
        }
    }
}

// ─── Plugin versions ──────────────────────────────────────────────────────────
plugins {
    id("com.android.application")              version "8.9.1"  apply false
    id("com.android.library")                  version "8.9.1"  apply false
 
    id("org.jetbrains.kotlin.android")         version "2.1.20" apply false
 
    id("org.jetbrains.kotlin.plugin.compose")  version "2.1.20" apply false
 
    id("com.google.gms.google-services")       version "4.4.2"  apply false
    id("com.google.firebase.crashlytics")      version "3.0.3"  apply false
   
    id("dev.flutter.flutter-plugin-loader")    version "1.0.0"
}

// ─── Project structure ────────────────────────────────────────────────────────
rootProject.name = "bd_news_reader"

include(":app")