// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHaDNvv-pLn4NYcpS139J2Bv6r2VQDA-g',
    appId: '1:92831175770:web:c9f2352eb095beec93f463',
    messagingSenderId: '92831175770',
    projectId: 'droid-e9db9',
    authDomain: 'droid-e9db9.firebaseapp.com',
    storageBucket: 'droid-e9db9.firebasestorage.app',
    measurementId: 'G-LKZEDMNFX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeSxbjb0TIYG0kWuLMm-j7TdbZ0nXt8go',
    appId: '1:92831175770:android:40fc17be01d7222293f463',
    messagingSenderId: '92831175770',
    projectId: 'droid-e9db9',
    storageBucket: 'droid-e9db9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Vsaayr2jDfB_FEyHQ7PCJ30A51WUsc8',
    appId: '1:92831175770:ios:b69407f94ea150b993f463',
    messagingSenderId: '92831175770',
    projectId: 'droid-e9db9',
    storageBucket: 'droid-e9db9.firebasestorage.app',
    iosBundleId: 'com.example.droid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Vsaayr2jDfB_FEyHQ7PCJ30A51WUsc8',
    appId: '1:92831175770:ios:b69407f94ea150b993f463',
    messagingSenderId: '92831175770',
    projectId: 'droid-e9db9',
    storageBucket: 'droid-e9db9.firebasestorage.app',
    iosBundleId: 'com.example.droid',
  );
}
