// Mocks generated by Mockito 5.4.4 from annotations
// in bdnewsreader/test/unit/services/rss_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:bdnewsreader/core/config/performance_config.dart' as _i5;
import 'package:bdnewsreader/core/telemetry/structured_logger.dart' as _i7;
import 'package:bdnewsreader/infrastructure/network/app_network_service.dart'
    as _i2;
import 'package:logger/logger.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppNetworkService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppNetworkService extends _i1.Mock implements _i2.AppNetworkService {
  MockAppNetworkService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i2.NetworkQuality get currentQuality => (super.noSuchMethod(
        Invocation.getter(#currentQuality),
        returnValue: _i2.NetworkQuality.excellent,
      ) as _i2.NetworkQuality);

  @override
  bool get isDebugOverrideActive => (super.noSuchMethod(
        Invocation.getter(#isDebugOverrideActive),
        returnValue: false,
      ) as bool);

  @override
  bool get isDebugSlowNetwork => (super.noSuchMethod(
        Invocation.getter(#isDebugSlowNetwork),
        returnValue: false,
      ) as bool);

  @override
  bool get isDebugOffline => (super.noSuchMethod(
        Invocation.getter(#isDebugOffline),
        returnValue: false,
      ) as bool);

  @override
  String get qualityDescription => (super.noSuchMethod(
        Invocation.getter(#qualityDescription),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#qualityDescription),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void registerRequestLatency(Duration? duration) => super.noSuchMethod(
        Invocation.method(
          #registerRequestLatency,
          [duration],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Duration getAdaptiveTimeout() => (super.noSuchMethod(
        Invocation.method(
          #getAdaptiveTimeout,
          [],
        ),
        returnValue: _FakeDuration_0(
          this,
          Invocation.method(
            #getAdaptiveTimeout,
            [],
          ),
        ),
      ) as Duration);

  @override
  int getFeedConcurrency() => (super.noSuchMethod(
        Invocation.method(
          #getFeedConcurrency,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int getImageCacheWidth({required bool? dataSaver}) => (super.noSuchMethod(
        Invocation.method(
          #getImageCacheWidth,
          [],
          {#dataSaver: dataSaver},
        ),
        returnValue: 0,
      ) as int);

  @override
  int getArticleLimit() => (super.noSuchMethod(
        Invocation.method(
          #getArticleLimit,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool shouldLoadImages({required bool? dataSaver}) => (super.noSuchMethod(
        Invocation.method(
          #shouldLoadImages,
          [],
          {#dataSaver: dataSaver},
        ),
        returnValue: false,
      ) as bool);

  @override
  Duration getCacheDuration() => (super.noSuchMethod(
        Invocation.method(
          #getCacheDuration,
          [],
        ),
        returnValue: _FakeDuration_0(
          this,
          Invocation.method(
            #getCacheDuration,
            [],
          ),
        ),
      ) as Duration);

  @override
  bool shouldPrefetch() => (super.noSuchMethod(
        Invocation.method(
          #shouldPrefetch,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void updatePerformanceTier(_i5.DevicePerformanceTier? tier) =>
      super.noSuchMethod(
        Invocation.method(
          #updatePerformanceTier,
          [tier],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void enableDebugSlowNetwork() => super.noSuchMethod(
        Invocation.method(
          #enableDebugSlowNetwork,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void enableDebugOfflineMode() => super.noSuchMethod(
        Invocation.method(
          #enableDebugOfflineMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearDebugOverride() => super.noSuchMethod(
        Invocation.method(
          #clearDebugOverride,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StructuredLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockStructuredLogger extends _i1.Mock implements _i7.StructuredLogger {
  MockStructuredLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void log(
    String? message, {
    _i8.Level? level = _i8.Level.info,
    Map<String, dynamic>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
          {
            #level: level,
            #context: context,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void info(
    String? message, [
    Map<String, dynamic>? context,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #info,
          [
            message,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warn(
    String? message, [
    Map<String, dynamic>? context,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #warn,
          [
            message,
            context,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void warning(
    String? message, [
    dynamic error,
    StackTrace? stack,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #warning,
          [
            message,
            error,
            stack,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void error(
    String? message, [
    dynamic error,
    StackTrace? stack,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #error,
          [
            message,
            error,
            stack,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
