// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

String? _dotenvValue(String key) {
  try {
    if (!dotenv.isInitialized) return null;
    return dotenv.env[key];
  } catch (_) {
    return null;
  }
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// / ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: _dotenvValue('FIREBASE_API_KEY_WEB') ?? 'MISSING_WEB_API_KEY',
    appId: _dotenvValue('FIREBASE_APP_ID_WEB') ?? 'MISSING_WEB_APP_ID',
    messagingSenderId:
        _dotenvValue('FIREBASE_MESSAGING_SENDER_ID') ?? 'MISSING_SENDER_ID',
    projectId: _dotenvValue('FIREBASE_PROJECT_ID') ?? 'bd-news-reader',
    authDomain: _dotenvValue('FIREBASE_AUTH_DOMAIN'),
    storageBucket: _dotenvValue('FIREBASE_STORAGE_BUCKET'),
    measurementId: _dotenvValue('FIREBASE_MEASUREMENT_ID'),
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey:
        _dotenvValue('FIREBASE_API_KEY_ANDROID') ?? 'MISSING_ANDROID_API_KEY',
    appId: _dotenvValue('FIREBASE_APP_ID_ANDROID') ?? 'MISSING_ANDROID_APP_ID',
    messagingSenderId:
        _dotenvValue('FIREBASE_MESSAGING_SENDER_ID') ?? 'MISSING_SENDER_ID',
    projectId: _dotenvValue('FIREBASE_PROJECT_ID') ?? 'bd-news-reader',
    storageBucket: _dotenvValue('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _dotenvValue('FIREBASE_API_KEY_IOS') ?? 'MISSING_IOS_API_KEY',
    appId: _dotenvValue('FIREBASE_APP_ID_IOS') ?? 'MISSING_IOS_APP_ID',
    messagingSenderId:
        _dotenvValue('FIREBASE_MESSAGING_SENDER_ID') ?? 'MISSING_SENDER_ID',
    projectId: _dotenvValue('FIREBASE_PROJECT_ID') ?? 'bd-news-reader',
    storageBucket: _dotenvValue('FIREBASE_STORAGE_BUCKET'),
    androidClientId: _dotenvValue('FIREBASE_ANDROID_CLIENT_ID'),
    iosClientId: _dotenvValue('FIREBASE_IOS_CLIENT_ID'),
    iosBundleId:
        _dotenvValue('FIREBASE_IOS_BUNDLE_ID') ?? 'com.bd.bdnewsreader',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: _dotenvValue('FIREBASE_API_KEY_IOS') ?? 'MISSING_MACOS_API_KEY',
    appId: _dotenvValue('FIREBASE_APP_ID_IOS') ?? 'MISSING_MACOS_APP_ID',
    messagingSenderId:
        _dotenvValue('FIREBASE_MESSAGING_SENDER_ID') ?? 'MISSING_SENDER_ID',
    projectId: _dotenvValue('FIREBASE_PROJECT_ID') ?? 'bd-news-reader',
    storageBucket: _dotenvValue('FIREBASE_STORAGE_BUCKET'),
    androidClientId: _dotenvValue('FIREBASE_ANDROID_CLIENT_ID'),
    iosClientId: _dotenvValue('FIREBASE_IOS_CLIENT_ID'),
    iosBundleId: _dotenvValue('FIREBASE_IOS_BUNDLE_ID'),
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: _dotenvValue('FIREBASE_API_KEY_WEB') ?? 'MISSING_WINDOWS_API_KEY',
    appId: _dotenvValue('FIREBASE_APP_ID_WEB') ?? 'MISSING_WINDOWS_APP_ID',
    messagingSenderId:
        _dotenvValue('FIREBASE_MESSAGING_SENDER_ID') ?? 'MISSING_SENDER_ID',
    projectId: _dotenvValue('FIREBASE_PROJECT_ID') ?? 'bd-news-reader',
    authDomain: _dotenvValue('FIREBASE_AUTH_DOMAIN'),
    storageBucket: _dotenvValue('FIREBASE_STORAGE_BUCKET'),
    measurementId: _dotenvValue('FIREBASE_MEASUREMENT_ID'),
  );
}
