// Mocks generated by Mockito 5.4.4 from annotations
// in bdnewsreader/test/unit/news_repository_mock_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:bdnewsreader/domain/entities/news_article.dart' as _i8;
import 'package:bdnewsreader/domain/services/ai_service.dart' as _i12;
import 'package:bdnewsreader/infrastructure/persistence/vault/vault_database.dart'
    as _i6;
import 'package:bdnewsreader/infrastructure/services/ml/news_feed_category_classifier.dart'
    as _i3;
import 'package:bdnewsreader/infrastructure/services/news/news_api_service.dart'
    as _i11;
import 'package:bdnewsreader/infrastructure/services/news/rss_service.dart'
    as _i7;
import 'package:flutter/widgets.dart' as _i10;
import 'package:logger/src/log_level.dart' as _i15;
import 'package:logger/src/logger.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:shared_preferences/shared_preferences.dart' as _i4;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTagDrivenCategorizationResult_1 extends _i1.SmartFake
    implements _i3.TagDrivenCategorizationResult {
  _FakeTagDrivenCategorizationResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i4.SharedPreferences {
  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getDouble,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getStringList,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as List<String>?);

  @override
  _i5.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [VaultDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultDatabase extends _i1.Mock implements _i6.VaultDatabase {
  @override
  _i5.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<void> writeDocument(
    String? collection,
    String? id,
    String? encryptedData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeDocument,
          [
            collection,
            id,
            encryptedData,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> readDocument(
    String? collection,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #readDocument,
          [
            collection,
            id,
          ],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<List<String>> readCollection(String? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #readCollection,
          [collection],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> deleteDocument(
    String? collection,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [
            collection,
            id,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [RssService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRssService extends _i1.Mock implements _i7.RssService {
  @override
  _i5.Future<List<_i8.NewsArticle>> fetchNews({
    required String? category,
    required _i9.Locale? locale,
    _i10.BuildContext? context,
    bool? preferRss = false,
    Set<String>? disabledUrls,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNews,
          [],
          {
            #category: category,
            #locale: locale,
            #context: context,
            #preferRss: preferRss,
            #disabledUrls: disabledUrls,
          },
        ),
        returnValue:
            _i5.Future<List<_i8.NewsArticle>>.value(<_i8.NewsArticle>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i8.NewsArticle>>.value(<_i8.NewsArticle>[]),
      ) as _i5.Future<List<_i8.NewsArticle>>);

  @override
  _i7.FeedRequestOutcome lastRequestOutcome({
    required String? category,
    required String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastRequestOutcome,
          [],
          {
            #category: category,
            #language: language,
          },
        ),
        returnValue: _i7.FeedRequestOutcome.successWithData,
        returnValueForMissingStub: _i7.FeedRequestOutcome.successWithData,
      ) as _i7.FeedRequestOutcome);

  @override
  bool wasLastFetchSuccessful({
    required String? category,
    required String? language,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #wasLastFetchSuccessful,
          [],
          {
            #category: category,
            #language: language,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [NewsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsApiService extends _i1.Mock implements _i11.NewsApiService {
  @override
  _i5.Future<List<_i8.NewsArticle>> fetchFromNewsData({
    required String? category,
    String? language = r'en',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFromNewsData,
          [],
          {
            #category: category,
            #language: language,
          },
        ),
        returnValue:
            _i5.Future<List<_i8.NewsArticle>>.value(<_i8.NewsArticle>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i8.NewsArticle>>.value(<_i8.NewsArticle>[]),
      ) as _i5.Future<List<_i8.NewsArticle>>);

  @override
  _i5.Future<List<_i8.NewsArticle>> fetchFromGNews({
    required String? category,
    String? language = r'en',
    String? country = r'bd',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFromGNews,
          [],
          {
            #category: category,
            #language: language,
            #country: country,
          },
        ),
        returnValue:
            _i5.Future<List<_i8.NewsArticle>>.value(<_i8.NewsArticle>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i8.NewsArticle>>.value(<_i8.NewsArticle>[]),
      ) as _i5.Future<List<_i8.NewsArticle>>);
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i12.AIService {
  @override
  _i5.Future<String> summarize(
    String? content, {
    _i12.SummaryType? type = _i12.SummaryType.detailed,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #summarize,
          [content],
          {#type: type},
        ),
        returnValue: _i5.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #summarize,
            [content],
            {#type: type},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #summarize,
            [content],
            {#type: type},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> explainComplexTerm(
    String? term,
    String? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #explainComplexTerm,
          [
            term,
            context,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #explainComplexTerm,
            [
              term,
              context,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #explainComplexTerm,
            [
              term,
              context,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<String>> generateTags(String? content) => (super.noSuchMethod(
        Invocation.method(
          #generateTags,
          [content],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  List<_i12.ExtractedTopic> extractTrendingTopics(
          List<Map<String, String>>? articles) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractTrendingTopics,
          [articles],
        ),
        returnValue: <_i12.ExtractedTopic>[],
        returnValueForMissingStub: <_i12.ExtractedTopic>[],
      ) as List<_i12.ExtractedTopic>);

  @override
  _i5.Future<String> summarizeArticle(String? content) => (super.noSuchMethod(
        Invocation.method(
          #summarizeArticle,
          [content],
        ),
        returnValue: _i5.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #summarizeArticle,
            [content],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i13.dummyValue<String>(
          this,
          Invocation.method(
            #summarizeArticle,
            [content],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [NewsFeedCategoryClassifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsFeedCategoryClassifier extends _i1.Mock
    implements _i3.NewsFeedCategoryClassifier {
  @override
  _i5.Future<_i3.TagDrivenCategorizationResult> classify({
    required String? title,
    required String? description,
    String? content,
    String? language = r'en',
    String? articleId,
    String? feedCategory,
    bool? collectAiSignals = true,
    void Function(Map<String, dynamic>)? onAiInsight,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #classify,
          [],
          {
            #title: title,
            #description: description,
            #content: content,
            #language: language,
            #articleId: articleId,
            #feedCategory: feedCategory,
            #collectAiSignals: collectAiSignals,
            #onAiInsight: onAiInsight,
          },
        ),
        returnValue: _i5.Future<_i3.TagDrivenCategorizationResult>.value(
            _FakeTagDrivenCategorizationResult_1(
          this,
          Invocation.method(
            #classify,
            [],
            {
              #title: title,
              #description: description,
              #content: content,
              #language: language,
              #articleId: articleId,
              #feedCategory: feedCategory,
              #collectAiSignals: collectAiSignals,
              #onAiInsight: onAiInsight,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.TagDrivenCategorizationResult>.value(
                _FakeTagDrivenCategorizationResult_1(
          this,
          Invocation.method(
            #classify,
            [],
            {
              #title: title,
              #description: description,
              #content: content,
              #language: language,
              #articleId: articleId,
              #feedCategory: feedCategory,
              #collectAiSignals: collectAiSignals,
              #onAiInsight: onAiInsight,
            },
          ),
        )),
      ) as _i5.Future<_i3.TagDrivenCategorizationResult>);

  @override
  void overrideTaxonomyForTesting(_i3.FeedCategoryTaxonomy? taxonomy) =>
      super.noSuchMethod(
        Invocation.method(
          #overrideTaxonomyForTesting,
          [taxonomy],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i14.Logger {
  @override
  _i5.Future<void> get init => (super.noSuchMethod(
        Invocation.getter(#init),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #v,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #t,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #d,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #i,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #w,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #e,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #wtf,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #f,
          [message],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void log(
    _i15.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #log,
          [
            level,
            message,
          ],
          {
            #time: time,
            #error: error,
            #stackTrace: stackTrace,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isClosed() => (super.noSuchMethod(
        Invocation.method(
          #isClosed,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
